dbConfig:
  dbConfigFile: plutus-pab.db
  dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://pab-executable:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5

walletServerConfig:
  baseUrl: http://cardano-wallet:8090
  wallet:
    getWallet: 1

nodeServerConfig:
  mscBaseUrl: http://cardano-node:3001
  mscSocketPath: /ipc/node.sock
    # mscBaseUrl: "cardano-node"
  mscKeptBlocks: 2160
  mscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  mscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  mscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  mscInitialTxWallets: []
  mscNodeMode: AlonzoNode

chainIndexConfig:
  ciBaseUrl: http://plutus-chain-index:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084 # change to proper service name
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085 # change to proper service name
# Optional EKG Server Config
# ----
# monitoringConfig:
#   monitoringPort: 9090
