version: "3.8"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.31.1
    volumes:
      - node-${NETWORK}-db:/node-db
      - node-ipc:/ipc
      - ./config:/config
    ports:
      - 3001:3001
    entrypoint: []
    command: bash -c "
      $$CMD --config /config/${NETWORK}/${NETWORK}-config.json --topology /config/${NETWORK}/${NETWORK}-topology.json
      "
    environment:
      CMD: "cardano-node run --socket-path /ipc/node.socket --database-path /node-db/node.db --port 3001"
      NETWORK:
    restart: on-failure
    logging: &logging
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-wallet:
    image: inputoutput/cardano-wallet:2021.11.11
    volumes:
      - wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
      - ./config:/config
    ports:
      - 8093:8090
    entrypoint: []
    command: bash -c "
      ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
      ($$CMD --testnet /config/${NETWORK}/${NETWORK}-byron-genesis.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure
    logging:
      <<: *logging

  plutus-chain-index:
    image: plutus4binarapps/dex-chain-index
    entrypoint: []
    volumes:
      # - chain-${NETWORK}-db:/chain-db
      - node-ipc:/ipc
      - ./config:/config
    ports:
      - 9083:9083
    command: bash -c "
      plutus-chain-index --config /config/${NETWORK}/chain-index-config.json --socket-path /ipc/node.socket --db-path /config/${NETWORK}/chain-index.db start-index
      "

  pab-executable:
    image: plutus4binarapps/dex-backend
    volumes:
      - node-ipc:/ipc
      - ./config:/config
    entrypoint: []
    command: bash -c "
      /bin/dex-pab --passphrase pab123456789 --config /config/${NETWORK}/pab-config.yml migrate &&
      /bin/dex-pab --passphrase pab123456789 --config /config/${NETWORK}/pab-config.yml webserver
      "
    environment:
      NETWORK:
    ports:
      - 9080:9080

  dex-middleware:
    image: plutus4binarapps/dex-middleware
    entrypoint: []
    command: middleware-manual
    ports:
      - 8080:8080

volumes:
  node-mainnet-db:
  node-testnet-db:
  node-alonzo-purple-db:
  wallet-mainnet-db:
  wallet-testnet-db:
  wallet-alonzo-purple-db:
  node-ipc:
  node-config:
  chain-testnet-db:
