version: '3'

services:
  faucet:
    image: plutus4binarapps/dex-faucet:latest
    tty: true
    ports:
      - "8085:8085"
    environment:
      - APP_FAUCET_WALLET_ADDRESS=$APP_FAUCET_WALLET_ADDRESS
    volumes:
      - ${FAUCET_WALLET_DIR}:/etc/faucet/wallet/
      - ${CARDANO_NODE_IPC_DIR}:/var/node-ipc
